#Sets if the plugin is enabled (teleports defaults to this area and helps them select kit
enabled: false


#Sets up the noob spawn location
noobspawn:
    world: world
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0

#Configuration for the kit that everybody gets: KIT NAME MUST BE COMPLETELY LOWERCASE
basekit-enable: false
basekit: tools

#Configuration for the kits that you choose 1 of: KIT NAME MUST BE COMPLETELY LOWERCASE
noobkits-enable: false
noobkits:
    - examplekit1
    - examplekit2

#Configuration for the starter pex rank to give them once they leave noob spawn
rank-enable: false
rank: Stowaway